apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  nodeName: ip-10-0-193-130.us-west-1.compute.internal
  containers:
  - image: quay.io/mayank123modi/mynginx
    name: pod
