apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress
  labels: 
   app: wordpress
spec:
  storageClassName: gp2
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs: 
   path: /nfs
   server: "54.219.212.4"
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqlpv
  labels: 
   app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs: 
   path: /nfs2
   server: "54.219.212.4"
  persistentVolumeReclaimPolicy: Retain
