apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlclaim
  labels:
    app: wordpress
spec:
  storageClass: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

